### ISSUE TITLE
Bug in TuioClient.java?

### ISSUE THREAD

**Issue by pequlius** [mkalten/TUIO11_JAVA#1]
I have had problems with array out of bounds exceptions when working with blobs in TUIO for Processing. I now think that I have tracked down the problem to a bug in the TuioClient class. The errors are between line 527-537, where there seem to be erroneous addressing to the argument array. The numbering goes directly from 1 to 3 making the length of the array 13 instead of 12 arguments. 
the code looks as follows:
                long s_id  = ((Integer)args[1]).longValue();
                float xpos = ((Float)args[3]).floatValue();
                float ypos = ((Float)args[4]).floatValue();
                float angle = ((Float)args[5]).floatValue();
                float width = ((Float)args[6]).floatValue();
                float height = ((Float)args[7]).floatValue();
                float area = ((Float)args[8]).floatValue();
                float xspeed = ((Float)args[9]).floatValue();
                float yspeed = ((Float)args[10]).floatValue();
                float rspeed = ((Float)args[11]).floatValue();
                float maccel = ((Float)args[12]).floatValue();
                float raccel = ((Float)args[13]).floatValue();

 Greetings
/Martin

**Comment by mkalten** [comment]
thanks for the heads up, it should be fixed now.
please let me know if you encounter further problems like that!
